/**
 * Ambient type declarations for Fachada virtual modules.
 *
 * These modules are resolved at build time by vite-plugin-fachada.
 * They are never present on disk — their content is generated by the plugin.
 */

declare module "virtual:fachada/active-app" {
  import type { AppConfig } from "../types/app.types";

  /** The build-time-selected AppConfig, resolved from .fachadarc.json + APP env var. */
  export const appConfig: AppConfig;

  /** Frozen array of all app names registered in .fachadarc.json. */
  export const AVAILABLE_APPS: readonly string[];
}
