/**
 * artist-engineer app config — Fachada v2 AppConfig package.
 *
 * Imports the artist-engineer profile configs (site + profile).
 * Adds 3 custom themes: minimal (clean/cool), warm (personal/human), bold (professional/strong).
 * Default theme: minimal
 *
 * Custom themes extend the global theme pool and are validated at build time for:
 * - Name collisions (custom theme name cannot override a global theme)
 * - defaultTheme existence (must be in the merged pool)
 * - Complete light/dark token sets (not partial overlays)
 */

import { siteConfig } from "../../src/profiles/artist-engineer-multi/site.config";
import { profileConfig } from "../../src/profiles/artist-engineer-multi/profile.config";
import type {
  AppConfig,
  CustomThemeDefinition,
} from "../../src/types/app.types";

export const appConfig: AppConfig = {
  seo: siteConfig,
  theme: profileConfig.theme,
  themes: {
    custom: {
      minimal: {
        name: "Minimal",
        description: "Clean and precise — cool sky blue accents",
        light: {
          bgPrimary: "#FFFFFF",
          bgSecondary: "#F8FAFC",
          textPrimary: "#0F172A",
          textSecondary: "#475569",
          accent: "#0EA5E9",
          accentHover: "#06B6D4",
          accentSecondary: "#06B6D4",
          accentTertiary: "#0284C7",
          border: "#E2E8F0",
          shadow: "rgba(0, 0, 0, 0.06)",
          borderRadius: "12px",
          transition: "0.25s ease-out",
          glow: "0 0 20px rgba(6, 182, 212, 0.2)",
          gradient: "linear-gradient(135deg, #0EA5E9 0%, #06B6D4 100%)",
          spacingSection: "5rem",
          spacingCard: "1.75rem",
          spacingElement: "1.25rem",
          fontBody: "'Inter', 'Helvetica Neue', Arial, sans-serif",
          fontHeading: "'Inter', 'Helvetica Neue', Arial, sans-serif",
          fontMono: "'JetBrains Mono', monospace",
          headingWeight: "600",
          bodyLineHeight: "1.7",
          contentMaxWidth: "960px",
          headingLetterSpacing: "-0.01em",
          buttonTextColor: "#0F172A",
          buttonTextShadow: "none",
          scanlineOpacity: "0",
        },
        dark: {
          bgPrimary: "#0F172A",
          bgSecondary: "#1E293B",
          textPrimary: "#F1F5F9",
          textSecondary: "#CBD5E1",
          accent: "#06D6FF",
          accentHover: "#00BBDF",
          accentSecondary: "#06D6FF",
          accentTertiary: "#0891B2",
          border: "#334155",
          shadow: "rgba(6, 214, 255, 0.15)",
          borderRadius: "12px",
          transition: "0.25s ease-out",
          glow: "0 0 20px rgba(6, 214, 255, 0.3)",
          gradient: "linear-gradient(135deg, #06D6FF 0%, #0891B2 100%)",
          spacingSection: "5rem",
          spacingCard: "1.75rem",
          spacingElement: "1.25rem",
          fontBody: "'Inter', 'Helvetica Neue', Arial, sans-serif",
          fontHeading: "'Inter', 'Helvetica Neue', Arial, sans-serif",
          fontMono: "'JetBrains Mono', monospace",
          headingWeight: "600",
          bodyLineHeight: "1.7",
          contentMaxWidth: "960px",
          headingLetterSpacing: "-0.01em",
          buttonTextColor: "#F1F5F9",
          buttonTextShadow: "none",
          scanlineOpacity: "0",
        },
      } as CustomThemeDefinition,
      warm: {
        name: "Warm",
        description: "Personal and human — warm amber accents",
        light: {
          bgPrimary: "#FFFBF0",
          bgSecondary: "#FFF7ED",
          textPrimary: "#451A03",
          textSecondary: "#92400E",
          accent: "#D97706",
          accentHover: "#F59E0B",
          accentSecondary: "#F97316",
          accentTertiary: "#DC2626",
          border: "#FDBF7D",
          shadow: "rgba(217, 119, 6, 0.1)",
          borderRadius: "16px",
          transition: "0.25s ease-out",
          glow: "0 0 20px rgba(217, 119, 6, 0.15)",
          gradient: "linear-gradient(135deg, #D97706 0%, #F59E0B 100%)",
          spacingSection: "5rem",
          spacingCard: "1.75rem",
          spacingElement: "1.25rem",
          fontBody: "'Inter', 'Helvetica Neue', Arial, sans-serif",
          fontHeading: "'Playfair Display', 'Georgia', serif",
          fontMono: "'JetBrains Mono', monospace",
          headingWeight: "600",
          bodyLineHeight: "1.85",
          contentMaxWidth: "960px",
          headingLetterSpacing: "-0.01em",
          buttonTextColor: "#451A03",
          buttonTextShadow: "none",
          scanlineOpacity: "0",
        },
        dark: {
          bgPrimary: "#2F1601",
          bgSecondary: "#422006",
          textPrimary: "#FED7AA",
          textSecondary: "#FDBA74",
          accent: "#F97316",
          accentHover: "#FB923C",
          accentSecondary: "#FCA5A5",
          accentTertiary: "#FCA5A5",
          border: "#D97706",
          shadow: "rgba(249, 115, 22, 0.15)",
          borderRadius: "16px",
          transition: "0.25s ease-out",
          glow: "0 0 20px rgba(249, 115, 22, 0.25)",
          gradient: "linear-gradient(135deg, #F97316 0%, #FB923C 100%)",
          spacingSection: "5rem",
          spacingCard: "1.75rem",
          spacingElement: "1.25rem",
          fontBody: "'Inter', 'Helvetica Neue', Arial, sans-serif",
          fontHeading: "'Playfair Display', 'Georgia', serif",
          fontMono: "'JetBrains Mono', monospace",
          headingWeight: "600",
          bodyLineHeight: "1.85",
          contentMaxWidth: "960px",
          headingLetterSpacing: "-0.01em",
          buttonTextColor: "#FED7AA",
          buttonTextShadow: "none",
          scanlineOpacity: "0",
        },
      } as CustomThemeDefinition,
      bold: {
        name: "Bold",
        description: "Professional and strong — vibrant purple accents",
        light: {
          bgPrimary: "#FAFAFA",
          bgSecondary: "#F4F4F5",
          textPrimary: "#1F2937",
          textSecondary: "#4B5563",
          accent: "#A855F7",
          accentHover: "#D946EF",
          accentSecondary: "#D946EF",
          accentTertiary: "#C084FC",
          border: "#D8BFD8",
          shadow: "rgba(168, 85, 247, 0.12)",
          borderRadius: "8px",
          transition: "0.25s ease-out",
          glow: "0 0 30px rgba(168, 85, 247, 0.2)",
          gradient: "linear-gradient(135deg, #A855F7 0%, #D946EF 100%)",
          spacingSection: "5rem",
          spacingCard: "1.75rem",
          spacingElement: "1.25rem",
          fontBody: "'Inter', 'Helvetica Neue', Arial, sans-serif",
          fontHeading: "'Space Grotesk', 'Inter', sans-serif",
          fontMono: "'JetBrains Mono', monospace",
          headingWeight: "700",
          bodyLineHeight: "1.7",
          contentMaxWidth: "960px",
          headingLetterSpacing: "-0.02em",
          buttonTextColor: "#1F2937",
          buttonTextShadow: "none",
          scanlineOpacity: "0",
        },
        dark: {
          bgPrimary: "#1E1E1E",
          bgSecondary: "#2D2D2D",
          textPrimary: "#F5F5F5",
          textSecondary: "#E0E0E0",
          accent: "#D946EF",
          accentHover: "#F472B6",
          accentSecondary: "#E879F9",
          accentTertiary: "#C084FC",
          border: "#6B21A8",
          shadow: "rgba(217, 70, 239, 0.2)",
          borderRadius: "8px",
          transition: "0.25s ease-out",
          glow: "0 0 30px rgba(217, 70, 239, 0.3)",
          gradient: "linear-gradient(135deg, #D946EF 0%, #F472B6 100%)",
          spacingSection: "5rem",
          spacingCard: "1.75rem",
          spacingElement: "1.25rem",
          fontBody: "'Inter', 'Helvetica Neue', Arial, sans-serif",
          fontHeading: "'Space Grotesk', 'Inter', sans-serif",
          fontMono: "'JetBrains Mono', monospace",
          headingWeight: "700",
          bodyLineHeight: "1.7",
          contentMaxWidth: "960px",
          headingLetterSpacing: "-0.02em",
          buttonTextColor: "#F5F5F5",
          buttonTextShadow: "none",
          scanlineOpacity: "0",
        },
      } as CustomThemeDefinition,
    },
    default: "minimal",
  },
  themeVariants: {},
  assets: {
    ogImage: siteConfig.ogImage,
  },
  page: {
    sections: profileConfig.sections.map((s) => ({ ...s, widgets: [] })),
  },
};
